/* eslint-disable react/prop-types */
/* eslint-disable react/no-unknown-property */
/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 bmw_m4_f82.glb 
*/
import * as THREE from "three"
import React, { useEffect } from 'react'
import { useGLTF, PerspectiveCamera, useAnimations } from '@react-three/drei'
import { useFrame } from '@react-three/fiber'
import model from '../../assets/3d assets/bmw_m4_f82.glb'

// eslint-disable-next-line react/prop-types, no-unused-vars
export function Model({ scroll, animationName, ...props   }) {
  const group = React.useRef();
  const { nodes, materials, animations } = useGLTF(model);
  const { actions } = useAnimations(animations, group);
  


  useEffect(() => void (actions[animationName].play().paused = true), [animationName])


  useFrame(() => {
    actions[animationName].time = THREE.MathUtils.lerp(actions[animationName].time, actions[animationName].getClip().duration * scroll.current, 0.05)
 
  })
  return (
    
     
    <group ref={group} {...props}   dispose={null}>
      <group name="Scene">
        <group name="Sketchfab_model" rotation={[-Math.PI / 2, 0, 0]}>
          <group name="F82fbx" rotation={[Math.PI / 2, 0, 0]} scale={0.01}>
            <group name="RootNode">
              <group name="amdb11_brakedisc_FR001" position={[75.519, 37.323, -150.797]} rotation={[Math.PI / 2, -0.035, Math.PI]} scale={105.483}>
                <mesh name="amdb11_brakedisc_FR001_amdb11_brake002_0" geometry={nodes.amdb11_brakedisc_FR001_amdb11_brake002_0.geometry} material={materials['amdb11_brake.002']} />
                <mesh name="amdb11_brakedisc_FR001_amdb11_caliper002_0" geometry={nodes.amdb11_brakedisc_FR001_amdb11_caliper002_0.geometry} material={materials['amdb11_caliper.002']} />
                <mesh name="amdb11_brakedisc_FR001_amdb11_misc002_0" geometry={nodes.amdb11_brakedisc_FR001_amdb11_misc002_0.geometry} material={materials['amdb11_misc.002']} />
                <mesh name="amdb11_brakedisc_FR001_amdb11_misc_chrome002_0" geometry={nodes.amdb11_brakedisc_FR001_amdb11_misc_chrome002_0.geometry} material={materials['amdb11_misc_chrome.002']} />
              </group>
              <group name="amdb11_brakedisc_FR002" position={[-75.261, 37.323, 130.31]} rotation={[-Math.PI / 2, -0.035, Math.PI]} scale={-105.483}>
                <mesh name="amdb11_brakedisc_FR002_amdb11_brake002_0" geometry={nodes.amdb11_brakedisc_FR002_amdb11_brake002_0.geometry} material={materials['amdb11_brake.002']} />
                <mesh name="amdb11_brakedisc_FR002_amdb11_caliper002_0" geometry={nodes.amdb11_brakedisc_FR002_amdb11_caliper002_0.geometry} material={materials['amdb11_caliper.002']} />
                <mesh name="amdb11_brakedisc_FR002_amdb11_misc002_0" geometry={nodes.amdb11_brakedisc_FR002_amdb11_misc002_0.geometry} material={materials['amdb11_misc.002']} />
                <mesh name="amdb11_brakedisc_FR002_amdb11_misc_chrome002_0" geometry={nodes.amdb11_brakedisc_FR002_amdb11_misc_chrome002_0.geometry} material={materials['amdb11_misc_chrome.002']} />
              </group>
              <group name="amdb11_brakedisc_FR003" position={[75.519, 37.323, 130.31]} rotation={[Math.PI / 2, -0.035, Math.PI]} scale={105.483}>
                <mesh name="amdb11_brakedisc_FR003_amdb11_brake002_0" geometry={nodes.amdb11_brakedisc_FR003_amdb11_brake002_0.geometry} material={materials['amdb11_brake.002']} />
                <mesh name="amdb11_brakedisc_FR003_amdb11_caliper002_0" geometry={nodes.amdb11_brakedisc_FR003_amdb11_caliper002_0.geometry} material={materials['amdb11_caliper.002']} />
                <mesh name="amdb11_brakedisc_FR003_amdb11_misc002_0" geometry={nodes.amdb11_brakedisc_FR003_amdb11_misc002_0.geometry} material={materials['amdb11_misc.002']} />
                <mesh name="amdb11_brakedisc_FR003_amdb11_misc_chrome002_0" geometry={nodes.amdb11_brakedisc_FR003_amdb11_misc_chrome002_0.geometry} material={materials['amdb11_misc_chrome.002']} />
              </group>
              <group name="amdb11_brakedisc_FR004" position={[-75.261, 37.323, -150.797]} rotation={[-Math.PI / 2, -0.035, Math.PI]} scale={-105.483}>
                <mesh name="amdb11_brakedisc_FR004_amdb11_brake002_0" geometry={nodes.amdb11_brakedisc_FR004_amdb11_brake002_0.geometry} material={materials['amdb11_brake.002']} />
                <mesh name="amdb11_brakedisc_FR004_amdb11_caliper002_0" geometry={nodes.amdb11_brakedisc_FR004_amdb11_caliper002_0.geometry} material={materials['amdb11_caliper.002']} />
                <mesh name="amdb11_brakedisc_FR004_amdb11_misc002_0" geometry={nodes.amdb11_brakedisc_FR004_amdb11_misc002_0.geometry} material={materials['amdb11_misc.002']} />
                <mesh name="amdb11_brakedisc_FR004_amdb11_misc_chrome002_0" geometry={nodes.amdb11_brakedisc_FR004_amdb11_misc_chrome002_0.geometry} material={materials['amdb11_misc_chrome.002']} />
              </group>
              <group name="ARm4_ariel" rotation={[-Math.PI / 2, 0, 0]} scale={100}>
                <mesh name="ARm4_ariel_ARm4_common_black_0" geometry={nodes.ARm4_ariel_ARm4_common_black_0.geometry} material={materials.ARm4_common_black} />
              </group>
              <group name="ARm4_backlight_tinted" rotation={[-Math.PI / 2, 0, 0]} scale={100}>
                <mesh name="ARm4_backlight_tinted_ARm4_glass_tinted_0" geometry={nodes.ARm4_backlight_tinted_ARm4_glass_tinted_0.geometry} material={materials.ARm4_glass_tinted} />
              </group>
              <group name="ARm4_body" rotation={[-Math.PI / 2, 0, 0]} scale={100}>
                <mesh name="ARm4_body_ARm4_main_0" geometry={nodes.ARm4_body_ARm4_main_0.geometry} material={materials.ARm4_main} />
                <mesh name="ARm4_body_ARm4_chmsl_0" geometry={nodes.ARm4_body_ARm4_chmsl_0.geometry} material={materials.ARm4_chmsl} />
                <mesh name="ARm4_body_ARm4_common_black_0" geometry={nodes.ARm4_body_ARm4_common_black_0.geometry} material={materials.ARm4_common_black} />
                <mesh name="ARm4_body_ARm4_Details_D_0" geometry={nodes.ARm4_body_ARm4_Details_D_0.geometry} material={materials.ARm4_Details_D} />
                <mesh name="ARm4_body_ARm4_INT_Decals_0" geometry={nodes.ARm4_body_ARm4_INT_Decals_0.geometry} material={materials.ARm4_INT_Decals} />
              </group>
              <group name="ARm4_brakepedal" position={[45.662, 59.259, 74.331]} rotation={[-Math.PI / 2, 0, 0]} scale={100}>
                <mesh name="ARm4_brakepedal_ARm4_common_black_0" geometry={nodes.ARm4_brakepedal_ARm4_common_black_0.geometry} material={materials.ARm4_common_black} />
                <mesh name="ARm4_brakepedal_ARm4_INT_Decals_0" geometry={nodes.ARm4_brakepedal_ARm4_INT_Decals_0.geometry} material={materials.ARm4_INT_Decals} />
              </group>
              <group name="ARm4_buckedseat_L" rotation={[-Math.PI / 2, 0, 0]} scale={100}>
                <mesh name="ARm4_buckedseat_L_ARm4_color_interior_0" geometry={nodes.ARm4_buckedseat_L_ARm4_color_interior_0.geometry} material={materials.ARm4_color_interior} />
                <mesh name="ARm4_buckedseat_L_ARm4_common_black_0" geometry={nodes.ARm4_buckedseat_L_ARm4_common_black_0.geometry} material={materials.ARm4_common_black} />
                <mesh name="ARm4_buckedseat_L_ARm4_common_carbon_0" geometry={nodes.ARm4_buckedseat_L_ARm4_common_carbon_0.geometry} material={materials.ARm4_common_carbon} />
                <mesh name="ARm4_buckedseat_L_ARm4_common_chrome_0" geometry={nodes.ARm4_buckedseat_L_ARm4_common_chrome_0.geometry} material={materials.ARm4_common_chrome} />
                <mesh name="ARm4_buckedseat_L_ARm4_INTER_tcz_0" geometry={nodes.ARm4_buckedseat_L_ARm4_INTER_tcz_0.geometry} material={materials.ARm4_INTER_tcz} />
              </group>
              <group name="ARm4_buckedseat_R" rotation={[-Math.PI / 2, 0, 0]} scale={100}>
                <mesh name="ARm4_buckedseat_R_ARm4_color_interior_0" geometry={nodes.ARm4_buckedseat_R_ARm4_color_interior_0.geometry} material={materials.ARm4_color_interior} />
                <mesh name="ARm4_buckedseat_R_ARm4_common_black_0" geometry={nodes.ARm4_buckedseat_R_ARm4_common_black_0.geometry} material={materials.ARm4_common_black} />
                <mesh name="ARm4_buckedseat_R_ARm4_common_carbon_0" geometry={nodes.ARm4_buckedseat_R_ARm4_common_carbon_0.geometry} material={materials.ARm4_common_carbon} />
                <mesh name="ARm4_buckedseat_R_ARm4_common_chrome_0" geometry={nodes.ARm4_buckedseat_R_ARm4_common_chrome_0.geometry} material={materials.ARm4_common_chrome} />
                <mesh name="ARm4_buckedseat_R_ARm4_INTER_tcz_0" geometry={nodes.ARm4_buckedseat_R_ARm4_INTER_tcz_0.geometry} material={materials.ARm4_INTER_tcz} />
              </group>
              <group name="ARm4_bumper_F" rotation={[-Math.PI / 2, 0, 0]} scale={100}>
                <mesh name="ARm4_bumper_F_ARm4_common_black_0" geometry={nodes.ARm4_bumper_F_ARm4_common_black_0.geometry} material={materials.ARm4_common_black} />
                <mesh name="ARm4_bumper_F_ARm4_main_0" geometry={nodes.ARm4_bumper_F_ARm4_main_0.geometry} material={materials.ARm4_main} />
              </group>
              <group name="ARm4_bumper_R" rotation={[-Math.PI / 2, 0, 0]} scale={100}>
                <mesh name="ARm4_bumper_R_ARm4_common_black_0" geometry={nodes.ARm4_bumper_R_ARm4_common_black_0.geometry} material={materials.ARm4_common_black} />
                <mesh name="ARm4_bumper_R_ARm4_Light_D_0" geometry={nodes.ARm4_bumper_R_ARm4_Light_D_0.geometry} material={materials.ARm4_Light_D} />
                <mesh name="ARm4_bumper_R_ARm4_main_0" geometry={nodes.ARm4_bumper_R_ARm4_main_0.geometry} material={materials.ARm4_main} />
                <mesh name="ARm4_bumper_R_ARm4_Metal_D_0" geometry={nodes.ARm4_bumper_R_ARm4_Metal_D_0.geometry} material={materials.ARm4_Metal_D} />
              </group>
              <group name="ARm4_bumper_Support" rotation={[-Math.PI / 2, 0, 0]} scale={100}>
                <mesh name="ARm4_bumper_Support_ARm4_common_black_0" geometry={nodes.ARm4_bumper_Support_ARm4_common_black_0.geometry} material={materials.ARm4_common_black} />
              </group>
              <group name="ARm4_canards_carbon" rotation={[-Math.PI / 2, 0, 0]} scale={100}>
                <mesh name="ARm4_canards_carbon_ARm4_common_black_0" geometry={nodes.ARm4_canards_carbon_ARm4_common_black_0.geometry} material={materials.ARm4_common_black} />
                <mesh name="ARm4_canards_carbon_ARm4_common_carbon_0" geometry={nodes.ARm4_canards_carbon_ARm4_common_carbon_0.geometry} material={materials.ARm4_common_carbon} />
              </group>
              <group name="ARm4_dender_trim_L" rotation={[-Math.PI / 2, 0, 0]} scale={100}>
                <mesh name="ARm4_dender_trim_L_ARm4_common_black_0" geometry={nodes.ARm4_dender_trim_L_ARm4_common_black_0.geometry} material={materials.ARm4_common_black} />
                <mesh name="ARm4_dender_trim_L_ARm4_common_chrome_0" geometry={nodes.ARm4_dender_trim_L_ARm4_common_chrome_0.geometry} material={materials.ARm4_common_chrome} />
              </group>
              <group name="ARm4_diff" rotation={[-Math.PI / 2, 0, 0]}>
                <mesh name="ARm4_diff_etkc_0" geometry={nodes.ARm4_diff_etkc_0.geometry} material={materials.etkc} />
              </group>
              <group name="ARm4_diff_F" rotation={[-Math.PI / 2, 0, 0]}>
                <mesh name="ARm4_diff_F_etkc_0" geometry={nodes.ARm4_diff_F_etkc_0.geometry} material={materials.etkc} />
              </group>
              <group name="ARm4_door_L" rotation={[-Math.PI / 2, 0, 0]} scale={100}>
                <mesh name="ARm4_door_L_ARm4_common_black_0" geometry={nodes.ARm4_door_L_ARm4_common_black_0.geometry} material={materials.ARm4_common_black} />
                <mesh name="ARm4_door_L_ARm4_common_metal_0" geometry={nodes.ARm4_door_L_ARm4_common_metal_0.geometry} material={materials.ARm4_common_metal} />
                <mesh name="ARm4_door_L_ARm4_main_0" geometry={nodes.ARm4_door_L_ARm4_main_0.geometry} material={materials.ARm4_main} />
                <mesh name="ARm4_door_L_etkc_0" geometry={nodes.ARm4_door_L_etkc_0.geometry} material={materials['etkc.001']} />
              </group>
              <group name="ARm4_door_L_handle_carbon" position={[0.134, 0, 0]} rotation={[-Math.PI / 2, 0, 0]} scale={100}>
                <mesh name="ARm4_door_L_handle_carbon_ARm4_common_carbon_0" geometry={nodes.ARm4_door_L_handle_carbon_ARm4_common_carbon_0.geometry} material={materials.ARm4_common_carbon} />
              </group>
              <group name="ARm4_door_R" rotation={[-Math.PI / 2, 0, 0]} scale={100}>
                <mesh name="ARm4_door_R_ARm4_common_black_0" geometry={nodes.ARm4_door_R_ARm4_common_black_0.geometry} material={materials.ARm4_common_black} />
                <mesh name="ARm4_door_R_ARm4_common_metal_0" geometry={nodes.ARm4_door_R_ARm4_common_metal_0.geometry} material={materials.ARm4_common_metal} />
                <mesh name="ARm4_door_R_ARm4_main_0" geometry={nodes.ARm4_door_R_ARm4_main_0.geometry} material={materials.ARm4_main} />
                <mesh name="ARm4_door_R_etkc_0" geometry={nodes.ARm4_door_R_etkc_0.geometry} material={materials['etkc.001']} />
              </group>
              <group name="ARm4_door_R_handle_carbon" position={[-0.163, 0, 0]} rotation={[-Math.PI / 2, 0, 0]} scale={100}>
                <mesh name="ARm4_door_R_handle_carbon_ARm4_common_carbon_0" geometry={nodes.ARm4_door_R_handle_carbon_ARm4_common_carbon_0.geometry} material={materials.ARm4_common_carbon} />
              </group>
              <group name="ARm4_doorglass_L" rotation={[-Math.PI / 2, 0, 0]} scale={100}>
                <mesh name="ARm4_doorglass_L_ARm4_glass_0" geometry={nodes.ARm4_doorglass_L_ARm4_glass_0.geometry} material={materials.ARm4_glass} />
              </group>
              <group name="ARm4_doorglass_R" rotation={[-Math.PI / 2, 0, 0]} scale={100}>
                <mesh name="ARm4_doorglass_R_ARm4_glass_0" geometry={nodes.ARm4_doorglass_R_ARm4_glass_0.geometry} material={materials.ARm4_glass} />
              </group>
              <group name="ARm4_doorpanel_L" rotation={[-Math.PI / 2, 0, 0]} scale={100}>
                <mesh name="ARm4_doorpanel_L_ARm4_color_interior_0" geometry={nodes.ARm4_doorpanel_L_ARm4_color_interior_0.geometry} material={materials.ARm4_color_interior} />
                <mesh name="ARm4_doorpanel_L_ARm4_common_black_0" geometry={nodes.ARm4_doorpanel_L_ARm4_common_black_0.geometry} material={materials.ARm4_common_black} />
                <mesh name="ARm4_doorpanel_L_ARm4_common_metal_0" geometry={nodes.ARm4_doorpanel_L_ARm4_common_metal_0.geometry} material={materials.ARm4_common_metal} />
                <mesh name="ARm4_doorpanel_L_ARm4_INT_Decals_0" geometry={nodes.ARm4_doorpanel_L_ARm4_INT_Decals_0.geometry} material={materials.ARm4_INT_Decals} />
                <mesh name="ARm4_doorpanel_L_ARm4_int_seams_0" geometry={nodes.ARm4_doorpanel_L_ARm4_int_seams_0.geometry} material={materials.ARm4_int_seams} />
                <mesh name="ARm4_doorpanel_L_ARm4_INT_speakers_0" geometry={nodes.ARm4_doorpanel_L_ARm4_INT_speakers_0.geometry} material={materials.ARm4_INT_speakers} />
                <mesh name="ARm4_doorpanel_L_ARm4_interior_symbols_0" geometry={nodes.ARm4_doorpanel_L_ARm4_interior_symbols_0.geometry} material={materials.ARm4_interior_symbols} />
              </group>
              <group name="ARm4_doorpanel_L_rgb" rotation={[-Math.PI / 2, 0, 0]} scale={100}>
                <mesh name="ARm4_doorpanel_L_rgb_ARm4_rgb_0" geometry={nodes.ARm4_doorpanel_L_rgb_ARm4_rgb_0.geometry} material={materials.ARm4_rgb} />
              </group>
              <group name="ARm4_doorpanel_R" rotation={[-Math.PI / 2, 0, 0]} scale={100}>
                <mesh name="ARm4_doorpanel_R_ARm4_color_interior_0" geometry={nodes.ARm4_doorpanel_R_ARm4_color_interior_0.geometry} material={materials.ARm4_color_interior} />
                <mesh name="ARm4_doorpanel_R_ARm4_common_black_0" geometry={nodes.ARm4_doorpanel_R_ARm4_common_black_0.geometry} material={materials.ARm4_common_black} />
                <mesh name="ARm4_doorpanel_R_ARm4_common_metal_0" geometry={nodes.ARm4_doorpanel_R_ARm4_common_metal_0.geometry} material={materials.ARm4_common_metal} />
                <mesh name="ARm4_doorpanel_R_ARm4_INT_Decals_0" geometry={nodes.ARm4_doorpanel_R_ARm4_INT_Decals_0.geometry} material={materials.ARm4_INT_Decals} />
                <mesh name="ARm4_doorpanel_R_ARm4_int_seams_0" geometry={nodes.ARm4_doorpanel_R_ARm4_int_seams_0.geometry} material={materials.ARm4_int_seams} />
                <mesh name="ARm4_doorpanel_R_ARm4_INT_speakers_0" geometry={nodes.ARm4_doorpanel_R_ARm4_INT_speakers_0.geometry} material={materials.ARm4_INT_speakers} />
                <mesh name="ARm4_doorpanel_R_ARm4_interior_symbols_0" geometry={nodes.ARm4_doorpanel_R_ARm4_interior_symbols_0.geometry} material={materials.ARm4_interior_symbols} />
              </group>
              <group name="ARm4_doorpanel_R_rgb" rotation={[-Math.PI / 2, 0, 0]} scale={100}>
                <mesh name="ARm4_doorpanel_R_rgb_ARm4_rgb_0" geometry={nodes.ARm4_doorpanel_R_rgb_ARm4_rgb_0.geometry} material={materials.ARm4_rgb} />
              </group>
              <group name="ARm4_driveshaft" position={[0, 33.102, -42.17]} rotation={[-Math.PI / 2, 0, 0]}>
                <mesh name="ARm4_driveshaft_etkc_0" geometry={nodes.ARm4_driveshaft_etkc_0.geometry} material={materials.etkc} />
              </group>
              <group name="ARm4_engine" rotation={[-Math.PI / 2, 0, 0]} scale={100}>
                <mesh name="ARm4_engine_ARm4_common_black_0" geometry={nodes.ARm4_engine_ARm4_common_black_0.geometry} material={materials.ARm4_common_black} />
                <mesh name="ARm4_engine_ARm4_common_chrome_0" geometry={nodes.ARm4_engine_ARm4_common_chrome_0.geometry} material={materials.ARm4_common_chrome} />
                <mesh name="ARm4_engine_ARm4_common_engine_0" geometry={nodes.ARm4_engine_ARm4_common_engine_0.geometry} material={materials.ARm4_common_engine} />
                <mesh name="ARm4_engine_ARm4_gray3_0" geometry={nodes.ARm4_engine_ARm4_gray3_0.geometry} material={materials.ARm4_gray3} />
                <mesh name="ARm4_engine_ARm4_Mpower_en_0" geometry={nodes.ARm4_engine_ARm4_Mpower_en_0.geometry} material={materials.ARm4_Mpower_en} />
              </group>
              <group name="ARm4_engine_i6" rotation={[-Math.PI / 2, 0, 0]}>
                <mesh name="ARm4_engine_i6_etk_engine_i6_0" geometry={nodes.ARm4_engine_i6_etk_engine_i6_0.geometry} material={materials.etk_engine_i6} />
              </group>
              <group name="ARm4_enginebay" rotation={[-Math.PI / 2, 0, 0]} scale={100}>
                <mesh name="ARm4_enginebay_ARm4_common_black_0" geometry={nodes.ARm4_enginebay_ARm4_common_black_0.geometry} material={materials.ARm4_common_black} />
                <mesh name="ARm4_enginebay_ARm4_common_carbon_0" geometry={nodes.ARm4_enginebay_ARm4_common_carbon_0.geometry} material={materials.ARm4_common_carbon} />
                <mesh name="ARm4_enginebay_ARm4_common_engine_0" geometry={nodes.ARm4_enginebay_ARm4_common_engine_0.geometry} material={materials.ARm4_common_engine} />
                <mesh name="ARm4_enginebay_ARm4_gray3_0" geometry={nodes.ARm4_enginebay_ARm4_gray3_0.geometry} material={materials.ARm4_gray3} />
                <mesh name="ARm4_enginebay_ARm4_main_0" geometry={nodes.ARm4_enginebay_ARm4_main_0.geometry} material={materials.ARm4_main} />
                <mesh name="ARm4_enginebay_ARm4_mechanicals_d_0" geometry={nodes.ARm4_enginebay_ARm4_mechanicals_d_0.geometry} material={materials.ARm4_mechanicals_d} />
              </group>
              <group name="ARm4_exhaust_L" rotation={[-Math.PI / 2, 0, 0]}>
                <mesh name="ARm4_exhaust_L_ARm4_common_black_0" geometry={nodes.ARm4_exhaust_L_ARm4_common_black_0.geometry} material={materials['ARm4_common_black.001']} />
                <mesh name="ARm4_exhaust_L_etkc_0" geometry={nodes.ARm4_exhaust_L_etkc_0.geometry} material={materials.etkc} />
              </group>
              <group name="ARm4_F_logo_M" position={[0, 0.013, 0]} rotation={[-Math.PI / 2, 0, 0]} scale={100}>
                <mesh name="ARm4_F_logo_M_ARm4_common_black_0" geometry={nodes.ARm4_F_logo_M_ARm4_common_black_0.geometry} material={materials.ARm4_common_black} />
                <mesh name="ARm4_F_logo_M_ARm4_m_bmw_logo_0" geometry={nodes.ARm4_F_logo_M_ARm4_m_bmw_logo_0.geometry} material={materials.ARm4_m_bmw_logo} />
              </group>
              <group name="ARm4_fender_L" rotation={[-Math.PI / 2, 0, 0]} scale={100}>
                <mesh name="ARm4_fender_L_ARm4_common_black_0" geometry={nodes.ARm4_fender_L_ARm4_common_black_0.geometry} material={materials.ARm4_common_black} />
                <mesh name="ARm4_fender_L_ARm4_Details_D_0" geometry={nodes.ARm4_fender_L_ARm4_Details_D_0.geometry} material={materials.ARm4_Details_D} />
                <mesh name="ARm4_fender_L_ARm4_main_0" geometry={nodes.ARm4_fender_L_ARm4_main_0.geometry} material={materials.ARm4_main} />
              </group>
              <group name="ARm4_fender_R" rotation={[-Math.PI / 2, 0, 0]} scale={100}>
                <mesh name="ARm4_fender_R_ARm4_common_black_0" geometry={nodes.ARm4_fender_R_ARm4_common_black_0.geometry} material={materials.ARm4_common_black} />
                <mesh name="ARm4_fender_R_ARm4_Details_D_0" geometry={nodes.ARm4_fender_R_ARm4_Details_D_0.geometry} material={materials.ARm4_Details_D} />
                <mesh name="ARm4_fender_R_ARm4_main_0" geometry={nodes.ARm4_fender_R_ARm4_main_0.geometry} material={materials.ARm4_main} />
              </group>
              <group name="ARm4_fender_trim_R" rotation={[-Math.PI / 2, 0, 0]} scale={100}>
                <mesh name="ARm4_fender_trim_R_ARm4_common_black_0" geometry={nodes.ARm4_fender_trim_R_ARm4_common_black_0.geometry} material={materials.ARm4_common_black} />
                <mesh name="ARm4_fender_trim_R_ARm4_common_chrome_0" geometry={nodes.ARm4_fender_trim_R_ARm4_common_chrome_0.geometry} material={materials.ARm4_common_chrome} />
              </group>
              <group name="ARm4_fender_trim_R_black" rotation={[-Math.PI / 2, 0, 0]} scale={100}>
                <mesh name="ARm4_fender_trim_R_black_ARm4_common_black_0" geometry={nodes.ARm4_fender_trim_R_black_ARm4_common_black_0.geometry} material={materials.ARm4_common_black} />
              </group>
              <group name="ARm4_gaspedal" position={[31.789, 30.306, 65.514]} rotation={[-Math.PI / 2, 0, 0]} scale={100}>
                <mesh name="ARm4_gaspedal_ARm4_INT_Decals_0" geometry={nodes.ARm4_gaspedal_ARm4_INT_Decals_0.geometry} material={materials.ARm4_INT_Decals} />
              </group>
              <group name="ARm4_grille_carbon001" position={[0, 0, -0.153]} rotation={[-Math.PI / 2, 0, 0]} scale={100}>
                <mesh name="ARm4_grille_carbon001_ARm4_common_metal_0" geometry={nodes.ARm4_grille_carbon001_ARm4_common_metal_0.geometry} material={materials.ARm4_common_metal} />
                <mesh name="ARm4_grille_carbon001_ARm4_Details_D_0" geometry={nodes.ARm4_grille_carbon001_ARm4_Details_D_0.geometry} material={materials.ARm4_Details_D} />
                <mesh name="ARm4_grille_carbon001_ARm4_forged_carbon_0" geometry={nodes.ARm4_grille_carbon001_ARm4_forged_carbon_0.geometry} material={materials.ARm4_forged_carbon} />
              </group>
              <group name="ARm4_gts_pad" rotation={[-Math.PI / 2, 0, 0]} scale={100}>
                <mesh name="ARm4_gts_pad_ARm4_common_black_0" geometry={nodes.ARm4_gts_pad_ARm4_common_black_0.geometry} material={materials.ARm4_common_black} />
              </group>
              <group name="ARm4_halfshaft_F" rotation={[-Math.PI / 2, 0, 0]}>
                <mesh name="ARm4_halfshaft_F_etkc_0" geometry={nodes.ARm4_halfshaft_F_etkc_0.geometry} material={materials.etkc} />
              </group>
              <group name="ARm4_halfshaft_R" rotation={[-Math.PI / 2, 0, 0]}>
                <mesh name="ARm4_halfshaft_R_etkc_0" geometry={nodes.ARm4_halfshaft_R_etkc_0.geometry} material={materials.etkc} />
              </group>
              <group name="ARm4_header_i6" rotation={[-Math.PI / 2, 0, 0]}>
                <mesh name="ARm4_header_i6_etk_engine_i6_0" geometry={nodes.ARm4_header_i6_etk_engine_i6_0.geometry} material={materials.etk_engine_i6} />
              </group>
              <group name="ARm4_header_i6_turbo" rotation={[-Math.PI / 2, 0, 0]}>
                <mesh name="ARm4_header_i6_turbo_etk_engine_i6_0" geometry={nodes.ARm4_header_i6_turbo_etk_engine_i6_0.geometry} material={materials.etk_engine_i6} />
              </group>
              <group name="ARm4_headlight_L_black" rotation={[-Math.PI / 2, 0, 0]} scale={100}>
                <mesh name="ARm4_headlight_L_black_ARm4_common_black_0" geometry={nodes.ARm4_headlight_L_black_ARm4_common_black_0.geometry} material={materials.ARm4_common_black} />
                <mesh name="ARm4_headlight_L_black_ARm4_glass_0" geometry={nodes.ARm4_headlight_L_black_ARm4_glass_0.geometry} material={materials.ARm4_glass} />
                <mesh name="ARm4_headlight_L_black_ARm4_headsignal_L_0" geometry={nodes.ARm4_headlight_L_black_ARm4_headsignal_L_0.geometry} material={materials.ARm4_headsignal_L} />
                <mesh name="ARm4_headlight_L_black_ARm4_highbeam_0" geometry={nodes.ARm4_headlight_L_black_ARm4_highbeam_0.geometry} material={materials.ARm4_highbeam} />
                <mesh name="ARm4_headlight_L_black_ARm4_Light_D_0" geometry={nodes.ARm4_headlight_L_black_ARm4_Light_D_0.geometry} material={materials.ARm4_Light_D} />
                <mesh name="ARm4_headlight_L_black_ARm4_lowbeam_0" geometry={nodes.ARm4_headlight_L_black_ARm4_lowbeam_0.geometry} material={materials.ARm4_lowbeam} />
                <mesh name="ARm4_headlight_L_black_ARm4_runninglight_0" geometry={nodes.ARm4_headlight_L_black_ARm4_runninglight_0.geometry} material={materials.ARm4_runninglight} />
                <mesh name="ARm4_headlight_L_black_ARm4_tailsignal_L_0" geometry={nodes.ARm4_headlight_L_black_ARm4_tailsignal_L_0.geometry} material={materials.ARm4_tailsignal_L} />
                <mesh name="ARm4_headlight_L_black_hedlight_o_0" geometry={nodes.ARm4_headlight_L_black_hedlight_o_0.geometry} material={materials.hedlight_o} />
              </group>
              <group name="ARm4_headlight_R_black" position={[0, 0, -0.267]} rotation={[-Math.PI / 2, 0, 0]} scale={100}>
                <mesh name="ARm4_headlight_R_black_ARm4_common_black_0" geometry={nodes.ARm4_headlight_R_black_ARm4_common_black_0.geometry} material={materials.ARm4_common_black} />
                <mesh name="ARm4_headlight_R_black_ARm4_glass_0" geometry={nodes.ARm4_headlight_R_black_ARm4_glass_0.geometry} material={materials.ARm4_glass} />
                <mesh name="ARm4_headlight_R_black_ARm4_headsignal_L_0" geometry={nodes.ARm4_headlight_R_black_ARm4_headsignal_L_0.geometry} material={materials.ARm4_headsignal_L} />
                <mesh name="ARm4_headlight_R_black_ARm4_highbeam_0" geometry={nodes.ARm4_headlight_R_black_ARm4_highbeam_0.geometry} material={materials.ARm4_highbeam} />
                <mesh name="ARm4_headlight_R_black_ARm4_Light_D_0" geometry={nodes.ARm4_headlight_R_black_ARm4_Light_D_0.geometry} material={materials.ARm4_Light_D} />
                <mesh name="ARm4_headlight_R_black_ARm4_lowbeam_0" geometry={nodes.ARm4_headlight_R_black_ARm4_lowbeam_0.geometry} material={materials.ARm4_lowbeam} />
                <mesh name="ARm4_headlight_R_black_ARm4_runninglight_0" geometry={nodes.ARm4_headlight_R_black_ARm4_runninglight_0.geometry} material={materials.ARm4_runninglight} />
                <mesh name="ARm4_headlight_R_black_ARm4_tailsignal_L_0" geometry={nodes.ARm4_headlight_R_black_ARm4_tailsignal_L_0.geometry} material={materials.ARm4_tailsignal_L} />
                <mesh name="ARm4_headlight_R_black_hedlight_o_0" geometry={nodes.ARm4_headlight_R_black_hedlight_o_0.geometry} material={materials.hedlight_o} />
              </group>
              <group name="ARm4_headlightglass_L" rotation={[-Math.PI / 2, 0, 0]} scale={100}>
                <mesh name="ARm4_headlightglass_L_ARm4_Light_D_0" geometry={nodes.ARm4_headlightglass_L_ARm4_Light_D_0.geometry} material={materials.ARm4_Light_D} />
              </group>
              <group name="ARm4_headlightglass_R" rotation={[-Math.PI / 2, 0, 0]} scale={100}>
                <mesh name="ARm4_headlightglass_R_ARm4_glass_0" geometry={nodes.ARm4_headlightglass_R_ARm4_glass_0.geometry} material={materials.ARm4_glass} />
              </group>
              <group name="ARm4_heatshield" rotation={[-Math.PI / 2, 0, 0]}>
                <mesh name="ARm4_heatshield_etkc_0" geometry={nodes.ARm4_heatshield_etkc_0.geometry} material={materials.etkc} />
              </group>
              <group name="ARm4_hood" rotation={[-Math.PI / 2, 0, 0]} scale={100}>
                <mesh name="ARm4_hood_ARm4_common_black_0" geometry={nodes.ARm4_hood_ARm4_common_black_0.geometry} material={materials.ARm4_common_black} />
                <mesh name="ARm4_hood_ARm4_common_chrome_0" geometry={nodes.ARm4_hood_ARm4_common_chrome_0.geometry} material={materials.ARm4_common_chrome} />
                <mesh name="ARm4_hood_ARm4_common_engine_0" geometry={nodes.ARm4_hood_ARm4_common_engine_0.geometry} material={materials.ARm4_common_engine} />
                <mesh name="ARm4_hood_ARm4_main_0" geometry={nodes.ARm4_hood_ARm4_main_0.geometry} material={materials.ARm4_main} />
              </group>
              <group name="ARm4_hub_F" rotation={[-Math.PI / 2, 0, 0]}>
                <mesh name="ARm4_hub_F_etkc_0" geometry={nodes.ARm4_hub_F_etkc_0.geometry} material={materials.etkc} />
              </group>
              <group name="ARm4_interior" rotation={[-Math.PI / 2, 0, 0]} scale={100}>
                <mesh name="ARm4_interior_ARm4_alcnt_0" geometry={nodes.ARm4_interior_ARm4_alcnt_0.geometry} material={materials.ARm4_alcnt} />
                <mesh name="ARm4_interior_ARm4_color_interior_0" geometry={nodes.ARm4_interior_ARm4_color_interior_0.geometry} material={materials.ARm4_color_interior} />
                <mesh name="ARm4_interior_ARm4_common_alum_0" geometry={nodes.ARm4_interior_ARm4_common_alum_0.geometry} material={materials.ARm4_common_alum} />
                <mesh name="ARm4_interior_ARm4_common_black_0" geometry={nodes.ARm4_interior_ARm4_common_black_0.geometry} material={materials.ARm4_common_black} />
                <mesh name="ARm4_interior_ARm4_common_carbon_0" geometry={nodes.ARm4_interior_ARm4_common_carbon_0.geometry} material={materials.ARm4_common_carbon} />
                <mesh name="ARm4_interior_ARm4_common_chrome_0" geometry={nodes.ARm4_interior_ARm4_common_chrome_0.geometry} material={materials.ARm4_common_chrome} />
                <mesh name="ARm4_interior_ARm4_common_metal_0" geometry={nodes.ARm4_interior_ARm4_common_metal_0.geometry} material={materials.ARm4_common_metal} />
                <mesh name="ARm4_interior_ARm4_crystal_interior_0" geometry={nodes.ARm4_interior_ARm4_crystal_interior_0.geometry} material={materials.ARm4_crystal_interior} />
                <mesh name="ARm4_interior_ARm4_grill_2_0" geometry={nodes.ARm4_interior_ARm4_grill_2_0.geometry} material={materials.ARm4_grill_2} />
                <mesh name="ARm4_interior_ARm4_INT_Belt_0" geometry={nodes.ARm4_interior_ARm4_INT_Belt_0.geometry} material={materials.ARm4_INT_Belt} />
                <mesh name="ARm4_interior_ARm4_INT_Decals_0" geometry={nodes.ARm4_interior_ARm4_INT_Decals_0.geometry} material={materials.ARm4_INT_Decals} />
                <mesh name="ARm4_interior_ARm4_int_decals_pad_0" geometry={nodes.ARm4_interior_ARm4_int_decals_pad_0.geometry} material={materials.ARm4_int_decals_pad} />
                <mesh name="ARm4_interior_ARm4_int_seams_0" geometry={nodes.ARm4_interior_ARm4_int_seams_0.geometry} material={materials.ARm4_int_seams} />
                <mesh name="ARm4_interior_ARm4_INT_speakers_0" geometry={nodes.ARm4_interior_ARm4_INT_speakers_0.geometry} material={materials.ARm4_INT_speakers} />
                <mesh name="ARm4_interior_ARm4_interior_black_0" geometry={nodes.ARm4_interior_ARm4_interior_black_0.geometry} material={materials.ARm4_interior_black} />
                <mesh name="ARm4_interior_ARm4_interior_hazard_0" geometry={nodes.ARm4_interior_ARm4_interior_hazard_0.geometry} material={materials.ARm4_interior_hazard} />
                <mesh name="ARm4_interior_ARm4_interior_symbols_0" geometry={nodes.ARm4_interior_ARm4_interior_symbols_0.geometry} material={materials.ARm4_interior_symbols} />
                <mesh name="ARm4_interior_ARm4_main_0" geometry={nodes.ARm4_interior_ARm4_main_0.geometry} material={materials.ARm4_main} />
                <mesh name="ARm4_interior_ARm4_wr_reset_badge_0" geometry={nodes.ARm4_interior_ARm4_wr_reset_badge_0.geometry} material={materials.ARm4_wr_reset_badge} />
                <mesh name="ARm4_interior_ARm4_wr_reset_badge_1_0" geometry={nodes.ARm4_interior_ARm4_wr_reset_badge_1_0.geometry} material={materials.ARm4_wr_reset_badge_1} />
                <mesh name="ARm4_interior_BMW_M4Coupe_2014_Badge_DiffuseAOSO_0" geometry={nodes.ARm4_interior_BMW_M4Coupe_2014_Badge_DiffuseAOSO_0.geometry} material={materials.BMW_M4Coupe_2014_Badge_DiffuseAOSO} />
                <mesh name="ARm4_interior_etkc_screen_0" geometry={nodes.ARm4_interior_etkc_screen_0.geometry} material={materials.etkc_screen} />
              </group>
              <group name="ARm4_interior_console_trim" rotation={[-Math.PI / 2, 0, 0]} scale={100}>
                <mesh name="ARm4_interior_console_trim_ARm4_common_black_0" geometry={nodes.ARm4_interior_console_trim_ARm4_common_black_0.geometry} material={materials.ARm4_common_black} />
              </group>
              <group name="ARm4_interior_console_trim_carbon" rotation={[-Math.PI / 2, 0, 0]} scale={100}>
                <mesh name="ARm4_interior_console_trim_carbon_ARm4_common_carbon_0" geometry={nodes.ARm4_interior_console_trim_carbon_ARm4_common_carbon_0.geometry} material={materials.ARm4_common_carbon} />
              </group>
              <group name="ARm4_interior_console_trim_forged" rotation={[-Math.PI / 2, 0, 0]} scale={100}>
                <mesh name="ARm4_interior_console_trim_forged_ARm4_forged_carbon_0" geometry={nodes.ARm4_interior_console_trim_forged_ARm4_forged_carbon_0.geometry} material={materials.ARm4_forged_carbon} />
              </group>
              <group name="ARm4_interior_headlight" position={[61.368, 85.159, 33.235]} rotation={[-Math.PI / 2, 0, 0]} scale={100}>
                <mesh name="ARm4_interior_headlight_ARm4_common_metal_0" geometry={nodes.ARm4_interior_headlight_ARm4_common_metal_0.geometry} material={materials.ARm4_common_metal} />
                <mesh name="ARm4_interior_headlight_ARm4_INT_Decals_0" geometry={nodes.ARm4_interior_headlight_ARm4_INT_Decals_0.geometry} material={materials.ARm4_INT_Decals} />
                <mesh name="ARm4_interior_headlight_ARm4_interior_symbols_0" geometry={nodes.ARm4_interior_headlight_ARm4_interior_symbols_0.geometry} material={materials.ARm4_interior_symbols} />
              </group>
              <group name="ARm4_interior_mirror" rotation={[-Math.PI / 2, 0, 0]} scale={100}>
                <mesh name="ARm4_interior_mirror_ARm4_common_black_0" geometry={nodes.ARm4_interior_mirror_ARm4_common_black_0.geometry} material={materials.ARm4_common_black} />
                <mesh name="ARm4_interior_mirror_mirror_0" geometry={nodes.ARm4_interior_mirror_mirror_0.geometry} material={materials.mirror} />
              </group>
              <group name="ARm4_interior_mirror_carbon" rotation={[-Math.PI / 2, 0, 0]} scale={100}>
                <mesh name="ARm4_interior_mirror_carbon_ARm4_common_carbon_0" geometry={nodes.ARm4_interior_mirror_carbon_ARm4_common_carbon_0.geometry} material={materials.ARm4_common_carbon} />
                <mesh name="ARm4_interior_mirror_carbon_mirror_0" geometry={nodes.ARm4_interior_mirror_carbon_mirror_0.geometry} material={materials.mirror} />
              </group>
              <group name="ARm4_interior_mirror_forged" rotation={[-Math.PI / 2, 0, 0]} scale={100}>
                <mesh name="ARm4_interior_mirror_forged_ARm4_forged_carbon_0" geometry={nodes.ARm4_interior_mirror_forged_ARm4_forged_carbon_0.geometry} material={materials.ARm4_forged_carbon} />
                <mesh name="ARm4_interior_mirror_forged_mirror_0" geometry={nodes.ARm4_interior_mirror_forged_mirror_0.geometry} material={materials.mirror} />
              </group>
              <group name="ARm4_interior_rgb" rotation={[-Math.PI / 2, 0, 0]} scale={100}>
                <mesh name="ARm4_interior_rgb_ARm4_rgb_0" geometry={nodes.ARm4_interior_rgb_ARm4_rgb_0.geometry} material={materials.ARm4_rgb} />
              </group>
              <group name="ARm4_interior_trim_black" rotation={[-Math.PI / 2, 0, 0]} scale={100}>
                <mesh name="ARm4_interior_trim_black_ARm4_common_black_0" geometry={nodes.ARm4_interior_trim_black_ARm4_common_black_0.geometry} material={materials.ARm4_common_black} />
                <mesh name="ARm4_interior_trim_black_ARm4_INT_Decals_0" geometry={nodes.ARm4_interior_trim_black_ARm4_INT_Decals_0.geometry} material={materials.ARm4_INT_Decals} />
              </group>
              <group name="ARm4_interior_trim_carbon" rotation={[-Math.PI / 2, 0, 0]} scale={100}>
                <mesh name="ARm4_interior_trim_carbon_ARm4_common_carbon_0" geometry={nodes.ARm4_interior_trim_carbon_ARm4_common_carbon_0.geometry} material={materials.ARm4_common_carbon} />
              </group>
              <group name="ARm4_interior_trim_forged" rotation={[-Math.PI / 2, 0, 0]} scale={100}>
                <mesh name="ARm4_interior_trim_forged_ARm4_forged_carbon_0" geometry={nodes.ARm4_interior_trim_forged_ARm4_forged_carbon_0.geometry} material={materials.ARm4_forged_carbon} />
              </group>
              <group name="ARm4_interior_upper_trim_black" rotation={[-Math.PI / 2, 0, 0]} scale={100}>
                <mesh name="ARm4_interior_upper_trim_black_ARm4_common_black_0" geometry={nodes.ARm4_interior_upper_trim_black_ARm4_common_black_0.geometry} material={materials.ARm4_common_black} />
              </group>
              <group name="ARm4_interior_upper_trim_carbon" rotation={[-Math.PI / 2, 0, 0]} scale={100}>
                <mesh name="ARm4_interior_upper_trim_carbon_ARm4_common_carbon_0" geometry={nodes.ARm4_interior_upper_trim_carbon_ARm4_common_carbon_0.geometry} material={materials.ARm4_common_carbon} />
              </group>
              <group name="ARm4_interior_upper_trim_forged" rotation={[-Math.PI / 2, 0, 0]} scale={100}>
                <mesh name="ARm4_interior_upper_trim_forged_ARm4_forged_carbon_0" geometry={nodes.ARm4_interior_upper_trim_forged_ARm4_forged_carbon_0.geometry} material={materials.ARm4_forged_carbon} />
              </group>
              <group name="ARm4_lip_carbon" position={[0, 0.148, -0.321]} rotation={[-Math.PI / 2, 0, 0]} scale={100}>
                <mesh name="ARm4_lip_carbon_ARm4_common_carbon_0" geometry={nodes.ARm4_lip_carbon_ARm4_common_carbon_0.geometry} material={materials.ARm4_common_carbon} />
              </group>
              <group name="ARm4_lowerarm_F_a" rotation={[-Math.PI / 2, 0, 0]}>
                <mesh name="ARm4_lowerarm_F_a_etkc_0" geometry={nodes.ARm4_lowerarm_F_a_etkc_0.geometry} material={materials.etkc} />
              </group>
              <group name="ARm4_lowerarm_F_b" rotation={[-Math.PI / 2, 0, 0]}>
                <mesh name="ARm4_lowerarm_F_b_etkc_0" geometry={nodes.ARm4_lowerarm_F_b_etkc_0.geometry} material={materials.etkc} />
              </group>
              <group name="ARm4_lowerarm_R" rotation={[-Math.PI / 2, 0, 0]}>
                <mesh name="ARm4_lowerarm_R_etkc_0" geometry={nodes.ARm4_lowerarm_R_etkc_0.geometry} material={materials.etkc} />
              </group>
              <group name="ARm4_m4_badge_black" rotation={[-Math.PI / 2, 0, 0]} scale={100}>
                <mesh name="ARm4_m4_badge_black_ARm4_common_black_0" geometry={nodes.ARm4_m4_badge_black_ARm4_common_black_0.geometry} material={materials.ARm4_common_black} />
                <mesh name="ARm4_m4_badge_black_ARm4_Details_D_0" geometry={nodes.ARm4_m4_badge_black_ARm4_Details_D_0.geometry} material={materials.ARm4_Details_D} />
              </group>
              <group name="ARm4_mirror_L_carbon" position={[0, 0.616, 0]} rotation={[-Math.PI / 2, 0, 0]} scale={100}>
                <mesh name="ARm4_mirror_L_carbon_ARm4_common_black_0" geometry={nodes.ARm4_mirror_L_carbon_ARm4_common_black_0.geometry} material={materials.ARm4_common_black} />
                <mesh name="ARm4_mirror_L_carbon_ARm4_common_carbon_0" geometry={nodes.ARm4_mirror_L_carbon_ARm4_common_carbon_0.geometry} material={materials.ARm4_common_carbon} />
                <mesh name="ARm4_mirror_L_carbon_ARm4_signal_L_0" geometry={nodes.ARm4_mirror_L_carbon_ARm4_signal_L_0.geometry} material={materials.ARm4_signal_L} />
                <mesh name="ARm4_mirror_L_carbon_mirror_0" geometry={nodes.ARm4_mirror_L_carbon_mirror_0.geometry} material={materials.mirror} />
              </group>
              <group name="ARm4_mirror_R_carbon" position={[0, 0.616, 0]} rotation={[-Math.PI / 2, 0, 0]} scale={100}>
                <mesh name="ARm4_mirror_R_carbon_ARm4_common_black_0" geometry={nodes.ARm4_mirror_R_carbon_ARm4_common_black_0.geometry} material={materials.ARm4_common_black} />
                <mesh name="ARm4_mirror_R_carbon_ARm4_common_carbon_0" geometry={nodes.ARm4_mirror_R_carbon_ARm4_common_carbon_0.geometry} material={materials.ARm4_common_carbon} />
                <mesh name="ARm4_mirror_R_carbon_ARm4_signal_R_0" geometry={nodes.ARm4_mirror_R_carbon_ARm4_signal_R_0.geometry} material={materials.ARm4_signal_R} />
                <mesh name="ARm4_mirror_R_carbon_mirror_0" geometry={nodes.ARm4_mirror_R_carbon_mirror_0.geometry} material={materials.mirror} />
              </group>
              <group name="ARm4_mudflaps_F_L" rotation={[-Math.PI / 2, 0, 0]} scale={100}>
                <mesh name="ARm4_mudflaps_F_L_ARm4_common_black_0" geometry={nodes.ARm4_mudflaps_F_L_ARm4_common_black_0.geometry} material={materials.ARm4_common_black} />
              </group>
              <group name="ARm4_mudflaps_F_R" rotation={[-Math.PI / 2, 0, 0]} scale={100}>
                <mesh name="ARm4_mudflaps_F_R_ARm4_common_black_0" geometry={nodes.ARm4_mudflaps_F_R_ARm4_common_black_0.geometry} material={materials.ARm4_common_black} />
              </group>
              <group name="ARm4_mudflaps_R" rotation={[-Math.PI / 2, 0, 0]} scale={100}>
                <mesh name="ARm4_mudflaps_R_ARm4_common_black_0" geometry={nodes.ARm4_mudflaps_R_ARm4_common_black_0.geometry} material={materials.ARm4_common_black} />
              </group>
              <group name="ARm4_needle_fuel" position={[49.184, 93.197, 41.626]} rotation={[-2.836, 0, 0]} scale={0.942}>
                <mesh name="ARm4_needle_fuel_etk_gauges_0" geometry={nodes.ARm4_needle_fuel_etk_gauges_0.geometry} material={materials.etk_gauges} />
              </group>
              <group name="ARm4_needle_speedo" position={[41.867, 96.078, 42.275]} rotation={[-2.907, 0, 0]} scale={0.942}>
                <mesh name="ARm4_needle_speedo_etk_gauges_0" geometry={nodes.ARm4_needle_speedo_etk_gauges_0.geometry} material={materials.etk_gauges} />
              </group>
              <group name="ARm4_needle_tacho" position={[29.175, 96.078, 42.275]} rotation={[-2.91, 0, 0]} scale={0.942}>
                <mesh name="ARm4_needle_tacho_etk_gauges_0" geometry={nodes.ARm4_needle_tacho_etk_gauges_0.geometry} material={materials.etk_gauges} />
              </group>
              <group name="ARm4_needle_temp" position={[21.886, 93.197, 41.626]} rotation={[-2.836, 0, 0]} scale={0.942}>
                <mesh name="ARm4_needle_temp_etk_gauges_0" geometry={nodes.ARm4_needle_temp_etk_gauges_0.geometry} material={materials.etk_gauges} />
              </group>
              <group name="ARm4_R_logo_M" position={[0, 0, 0.109]} rotation={[-Math.PI / 2, 0, 0]} scale={100}>
                <mesh name="ARm4_R_logo_M_ARm4_common_black_0" geometry={nodes.ARm4_R_logo_M_ARm4_common_black_0.geometry} material={materials.ARm4_common_black} />
                <mesh name="ARm4_R_logo_M_ARm4_m_bmw_logo_0" geometry={nodes.ARm4_R_logo_M_ARm4_m_bmw_logo_0.geometry} material={materials.ARm4_m_bmw_logo} />
              </group>
              <group name="ARm4_rear_diffuser_stock" rotation={[-Math.PI / 2, 0, 0]} scale={100}>
                <mesh name="ARm4_rear_diffuser_stock_ARm4_common_black_0" geometry={nodes.ARm4_rear_diffuser_stock_ARm4_common_black_0.geometry} material={materials.ARm4_common_black} />
                <mesh name="ARm4_rear_diffuser_stock_ARm4_common_chrome_0" geometry={nodes.ARm4_rear_diffuser_stock_ARm4_common_chrome_0.geometry} material={materials.ARm4_common_chrome} />
              </group>
              <group name="ARm4_roof" rotation={[-Math.PI / 2, 0, 0]} scale={100}>
                <mesh name="ARm4_roof_ARm4_common_carbon_0" geometry={nodes.ARm4_roof_ARm4_common_carbon_0.geometry} material={materials.ARm4_common_carbon} />
              </group>
              <group name="ARm4_seats_R" rotation={[-Math.PI / 2, 0, 0]} scale={100}>
                <mesh name="ARm4_seats_R_ARm4_color_interior_0" geometry={nodes.ARm4_seats_R_ARm4_color_interior_0.geometry} material={materials.ARm4_color_interior} />
                <mesh name="ARm4_seats_R_ARm4_common_black_0" geometry={nodes.ARm4_seats_R_ARm4_common_black_0.geometry} material={materials.ARm4_common_black} />
                <mesh name="ARm4_seats_R_ARm4_common_chrome_0" geometry={nodes.ARm4_seats_R_ARm4_common_chrome_0.geometry} material={materials.ARm4_common_chrome} />
                <mesh name="ARm4_seats_R_ARm4_INT_Belt_0" geometry={nodes.ARm4_seats_R_ARm4_INT_Belt_0.geometry} material={materials.ARm4_INT_Belt} />
                <mesh name="ARm4_seats_R_ARm4_INT_Decals_0" geometry={nodes.ARm4_seats_R_ARm4_INT_Decals_0.geometry} material={materials.ARm4_INT_Decals} />
                <mesh name="ARm4_seats_R_ARm4_int_seams_0" geometry={nodes.ARm4_seats_R_ARm4_int_seams_0.geometry} material={materials.ARm4_int_seams} />
                <mesh name="ARm4_seats_R_ARm4_INTER_tcz_0" geometry={nodes.ARm4_seats_R_ARm4_INTER_tcz_0.geometry} material={materials.ARm4_INTER_tcz} />
              </group>
              <group name="ARm4_shock_R" rotation={[-Math.PI / 2, 0, 0]}>
                <mesh name="ARm4_shock_R_etkc_0" geometry={nodes.ARm4_shock_R_etkc_0.geometry} material={materials.etkc} />
              </group>
              <group name="ARm4_sideglass_L_tinted" rotation={[-Math.PI / 2, 0, 0]} scale={100}>
                <mesh name="ARm4_sideglass_L_tinted_ARm4_glass_tinted_0" geometry={nodes.ARm4_sideglass_L_tinted_ARm4_glass_tinted_0.geometry} material={materials.ARm4_glass_tinted} />
              </group>
              <group name="ARm4_sideglass_R_tinted" rotation={[-Math.PI / 2, 0, 0]} scale={100}>
                <mesh name="ARm4_sideglass_R_tinted_ARm4_glass_tinted_0" geometry={nodes.ARm4_sideglass_R_tinted_ARm4_glass_tinted_0.geometry} material={materials.ARm4_glass_tinted} />
              </group>
              <group name="ARm4_signalstalk" position={[45.04, 88.717, 27.548]} rotation={[-Math.PI / 2, 0, 0]} scale={100}>
                <mesh name="ARm4_signalstalk_ARm4_common_black_0" geometry={nodes.ARm4_signalstalk_ARm4_common_black_0.geometry} material={materials.ARm4_common_black} />
                <mesh name="ARm4_signalstalk_ARm4_interior_symbols_0" geometry={nodes.ARm4_signalstalk_ARm4_interior_symbols_0.geometry} material={materials.ARm4_interior_symbols} />
              </group>
              <group name="ARm4_skirt_race" rotation={[-Math.PI / 2, 0, 0]} scale={100}>
                <mesh name="ARm4_skirt_race_ARm4_main_0" geometry={nodes.ARm4_skirt_race_ARm4_main_0.geometry} material={materials.ARm4_main} />
              </group>
              <group name="ARm4_splitter_street_carbon" position={[0, -0.199, 0]} rotation={[-Math.PI / 2, 0, 0]} scale={100}>
                <mesh name="ARm4_splitter_street_carbon_ARm4_common_carbon_0" geometry={nodes.ARm4_splitter_street_carbon_ARm4_common_carbon_0.geometry} material={materials.ARm4_common_carbon} />
              </group>
              <group name="ARm4_spring_R" rotation={[-Math.PI / 2, 0, 0]}>
                <mesh name="ARm4_spring_R_etkc_0" geometry={nodes.ARm4_spring_R_etkc_0.geometry} material={materials.etkc} />
              </group>
              <group name="ARm4_steer_carbon" position={[36.114, 93.337, 14.33]} rotation={[-1.134, 0, 0]} scale={100}>
                <mesh name="ARm4_steer_carbon_ARm4_common_black003_0" geometry={nodes.ARm4_steer_carbon_ARm4_common_black003_0.geometry} material={materials['ARm4_common_black.003']} />
                <mesh name="ARm4_steer_carbon_ARm4_common_bmw_logo_0" geometry={nodes.ARm4_steer_carbon_ARm4_common_bmw_logo_0.geometry} material={materials.ARm4_common_bmw_logo} />
                <mesh name="ARm4_steer_carbon_ARm4_common_carbon_0" geometry={nodes.ARm4_steer_carbon_ARm4_common_carbon_0.geometry} material={materials.ARm4_common_carbon} />
                <mesh name="ARm4_steer_carbon_ARm4_common_chrome_0" geometry={nodes.ARm4_steer_carbon_ARm4_common_chrome_0.geometry} material={materials.ARm4_common_chrome} />
                <mesh name="ARm4_steer_carbon_ARm4_common_metal_0" geometry={nodes.ARm4_steer_carbon_ARm4_common_metal_0.geometry} material={materials.ARm4_common_metal} />
                <mesh name="ARm4_steer_carbon_ARm4_INT_Decals_0" geometry={nodes.ARm4_steer_carbon_ARm4_INT_Decals_0.geometry} material={materials.ARm4_INT_Decals} />
                <mesh name="ARm4_steer_carbon_ARm4_interior_symbols_0" geometry={nodes.ARm4_steer_carbon_ARm4_interior_symbols_0.geometry} material={materials.ARm4_interior_symbols} />
                <mesh name="ARm4_steer_carbon_common_transparent_0" geometry={nodes.ARm4_steer_carbon_common_transparent_0.geometry} material={materials.common_transparent} />
              </group>
              <group name="ARm4_steer_stick_msport" position={[36.114, 93.38, 14.278]} rotation={[-1.134, 0, 0]} scale={[100, 99.966, 99.842]}>
                <mesh name="ARm4_steer_stick_msport_ARm4_int_seams_0" geometry={nodes.ARm4_steer_stick_msport_ARm4_int_seams_0.geometry} material={materials.ARm4_int_seams} />
                <mesh name="ARm4_steer_stick_msport_common_transparent_0" geometry={nodes.ARm4_steer_stick_msport_common_transparent_0.geometry} material={materials.common_transparent} />
              </group>
              <group name="ARm4_steeringbox" rotation={[-Math.PI / 2, 0, 0]}>
                <mesh name="ARm4_steeringbox_etkc_0" geometry={nodes.ARm4_steeringbox_etkc_0.geometry} material={materials.etkc} />
              </group>
              <group name="ARm4_strut_F" rotation={[-Math.PI / 2, 0, 0]}>
                <mesh name="ARm4_strut_F_etkc_0" geometry={nodes.ARm4_strut_F_etkc_0.geometry} material={materials.etkc} />
              </group>
              <group name="ARm4_subframe_F" rotation={[-Math.PI / 2, 0, 0]}>
                <mesh name="ARm4_subframe_F_etkc_0" geometry={nodes.ARm4_subframe_F_etkc_0.geometry} material={materials.etkc} />
              </group>
              <group name="ARm4_subframe_R" rotation={[-Math.PI / 2, 0, 0]}>
                <mesh name="ARm4_subframe_R_etkc_0" geometry={nodes.ARm4_subframe_R_etkc_0.geometry} material={materials.etkc} />
              </group>
              <group name="ARm4_sunvisor_L" rotation={[-Math.PI / 2, 0, 0]} scale={100}>
                <mesh name="ARm4_sunvisor_L_ARm4_common_black_0" geometry={nodes.ARm4_sunvisor_L_ARm4_common_black_0.geometry} material={materials.ARm4_common_black} />
              </group>
              <group name="ARm4_sunvisor_R" rotation={[-Math.PI / 2, 0, 0]} scale={100}>
                <mesh name="ARm4_sunvisor_R_ARm4_common_black_0" geometry={nodes.ARm4_sunvisor_R_ARm4_common_black_0.geometry} material={materials.ARm4_common_black} />
              </group>
              <group name="ARm4_swaybar_F" rotation={[-Math.PI / 2, 0, 0]}>
                <mesh name="ARm4_swaybar_F_etkc_0" geometry={nodes.ARm4_swaybar_F_etkc_0.geometry} material={materials.etkc} />
              </group>
              <group name="ARm4_taillight_L_snake001" position={[0, 0, -0.094]} rotation={[-Math.PI / 2, 0, 0]} scale={100}>
                <mesh name="ARm4_taillight_L_snake001_ARm4_common_black001_0" geometry={nodes.ARm4_taillight_L_snake001_ARm4_common_black001_0.geometry} material={materials['ARm4_common_black.002']} />
                <mesh name="ARm4_taillight_L_snake001_ARm4_headsignal_L_alt001_0" geometry={nodes.ARm4_taillight_L_snake001_ARm4_headsignal_L_alt001_0.geometry} material={materials['ARm4_headsignal_L_alt.001']} />
                <mesh name="ARm4_taillight_L_snake001_ARm4_taillight_alt001_0" geometry={nodes.ARm4_taillight_L_snake001_ARm4_taillight_alt001_0.geometry} material={materials['ARm4_taillight_alt.001']} />
              </group>
              <group name="ARm4_taillight_R_snake001" position={[0, 0, -0.094]} rotation={[-Math.PI / 2, 0, 0]} scale={100}>
                <mesh name="ARm4_taillight_R_snake001_ARm4_common_black001_0" geometry={nodes.ARm4_taillight_R_snake001_ARm4_common_black001_0.geometry} material={materials['ARm4_common_black.002']} />
                <mesh name="ARm4_taillight_R_snake001_ARm4_headsignal_L_alt001_0" geometry={nodes.ARm4_taillight_R_snake001_ARm4_headsignal_L_alt001_0.geometry} material={materials['ARm4_headsignal_L_alt.001']} />
                <mesh name="ARm4_taillight_R_snake001_ARm4_taillight_alt001_0" geometry={nodes.ARm4_taillight_R_snake001_ARm4_taillight_alt001_0.geometry} material={materials['ARm4_taillight_alt.001']} />
              </group>
              <group name="ARm4_taillightglass_L_tinted" position={[0, 0, -0.128]} rotation={[-Math.PI / 2, 0, 0]} scale={100}>
                <mesh name="ARm4_taillightglass_L_tinted_ARm4_glass_head_tinted_0" geometry={nodes.ARm4_taillightglass_L_tinted_ARm4_glass_head_tinted_0.geometry} material={materials.ARm4_glass_head_tinted} />
              </group>
              <group name="ARm4_taillightglass_R_tinted" position={[0, 0, -0.128]} rotation={[-Math.PI / 2, 0, 0]} scale={100}>
                <mesh name="ARm4_taillightglass_R_tinted_ARm4_glass_head_tinted_0" geometry={nodes.ARm4_taillightglass_R_tinted_ARm4_glass_head_tinted_0.geometry} material={materials.ARm4_glass_head_tinted} />
              </group>
              <group name="ARm4_tierod_F" rotation={[-Math.PI / 2, 0, 0]}>
                <mesh name="ARm4_tierod_F_etkc_0" geometry={nodes.ARm4_tierod_F_etkc_0.geometry} material={materials.etkc} />
              </group>
              <group name="ARm4_transfercase" rotation={[-Math.PI / 2, 0, 0]}>
                <mesh name="ARm4_transfercase_etkc_0" geometry={nodes.ARm4_transfercase_etkc_0.geometry} material={materials.etkc} />
              </group>
              <group name="ARm4_transmission" rotation={[-Math.PI / 2, 0, 0]}>
                <mesh name="ARm4_transmission_etkc_0" geometry={nodes.ARm4_transmission_etkc_0.geometry} material={materials.etkc} />
              </group>
              <group name="ARm4_trunk" rotation={[-Math.PI / 2, 0, 0]} scale={100}>
                <mesh name="ARm4_trunk_ARm4_alcnt_0" geometry={nodes.ARm4_trunk_ARm4_alcnt_0.geometry} material={materials.ARm4_alcnt} />
                <mesh name="ARm4_trunk_ARm4_common_black_0" geometry={nodes.ARm4_trunk_ARm4_common_black_0.geometry} material={materials.ARm4_common_black} />
                <mesh name="ARm4_trunk_ARm4_lowbeam_0" geometry={nodes.ARm4_trunk_ARm4_lowbeam_0.geometry} material={materials.ARm4_lowbeam} />
                <mesh name="ARm4_trunk_ARm4_main_0" geometry={nodes.ARm4_trunk_ARm4_main_0.geometry} material={materials.ARm4_main} />
              </group>
              <group name="ARm4_trunklight_L_tinted" position={[0, 0, -0.128]} rotation={[-Math.PI / 2, 0, 0]} scale={100}>
                <mesh name="ARm4_trunklight_L_tinted_ARm4_glass_head_tinted_0" geometry={nodes.ARm4_trunklight_L_tinted_ARm4_glass_head_tinted_0.geometry} material={materials.ARm4_glass_head_tinted} />
              </group>
              <group name="ARm4_trunklight_R_tinted" position={[0, 0, -0.128]} rotation={[-Math.PI / 2, 0, 0]} scale={100}>
                <mesh name="ARm4_trunklight_R_tinted_ARm4_glass_head_tinted_0" geometry={nodes.ARm4_trunklight_R_tinted_ARm4_glass_head_tinted_0.geometry} material={materials.ARm4_glass_head_tinted} />
              </group>
              <group name="ARm4_trunklight_snake001" position={[0, 0, -0.094]} rotation={[-Math.PI / 2, 0, 0]} scale={100}>
                <mesh name="ARm4_trunklight_snake001_ARm4_common_black001_0" geometry={nodes.ARm4_trunklight_snake001_ARm4_common_black001_0.geometry} material={materials['ARm4_common_black.002']} />
                <mesh name="ARm4_trunklight_snake001_ARm4_headsignal_L_alt001_0" geometry={nodes.ARm4_trunklight_snake001_ARm4_headsignal_L_alt001_0.geometry} material={materials['ARm4_headsignal_L_alt.001']} />
                <mesh name="ARm4_trunklight_snake001_ARm4_rev001_0" geometry={nodes.ARm4_trunklight_snake001_ARm4_rev001_0.geometry} material={materials['ARm4_rev.001']} />
                <mesh name="ARm4_trunklight_snake001_ARm4_taillight_alt001_0" geometry={nodes.ARm4_trunklight_snake001_ARm4_taillight_alt001_0.geometry} material={materials['ARm4_taillight_alt.001']} />
              </group>
              <group name="ARm4_underbody" rotation={[-Math.PI / 2, 0, 0]}>
                <mesh name="ARm4_underbody_etkc_0" geometry={nodes.ARm4_underbody_etkc_0.geometry} material={materials.etkc} />
              </group>
              <group name="ARm4_upperarm_R" rotation={[-Math.PI / 2, 0, 0]}>
                <mesh name="ARm4_upperarm_R_etkc_0" geometry={nodes.ARm4_upperarm_R_etkc_0.geometry} material={materials.etkc} />
              </group>
              <group name="ARm4_vt_wheel" position={[74.986, 37.323, 130.31]} rotation={[-Math.PI / 2, 0, 0]} scale={106.747}>
                <mesh name="ARm4_vt_wheel_ARm4_common_black_0" geometry={nodes.ARm4_vt_wheel_ARm4_common_black_0.geometry} material={materials.ARm4_common_black} />
                <mesh name="ARm4_vt_wheel_ARm4_main_0" geometry={nodes.ARm4_vt_wheel_ARm4_main_0.geometry} material={materials.ARm4_main} />
                <mesh name="ARm4_vt_wheel_ARm4_V_logo_0" geometry={nodes.ARm4_vt_wheel_ARm4_V_logo_0.geometry} material={materials.ARm4_V_logo} />
                <mesh name="ARm4_vt_wheel_michelin_diff_0" geometry={nodes.ARm4_vt_wheel_michelin_diff_0.geometry} material={materials.michelin_diff} />
              </group>
              <group name="ARm4_vt_wheel001" position={[74.986, 37.323, -150.797]} rotation={[-Math.PI / 2, 0, 0]} scale={106.747}>
                <mesh name="ARm4_vt_wheel001_ARm4_common_black_0" geometry={nodes.ARm4_vt_wheel001_ARm4_common_black_0.geometry} material={materials.ARm4_common_black} />
                <mesh name="ARm4_vt_wheel001_ARm4_main_0" geometry={nodes.ARm4_vt_wheel001_ARm4_main_0.geometry} material={materials.ARm4_main} />
                <mesh name="ARm4_vt_wheel001_ARm4_V_logo_0" geometry={nodes.ARm4_vt_wheel001_ARm4_V_logo_0.geometry} material={materials.ARm4_V_logo} />
                <mesh name="ARm4_vt_wheel001_michelin_diff_0" geometry={nodes.ARm4_vt_wheel001_michelin_diff_0.geometry} material={materials.michelin_diff} />
              </group>
              <group name="ARm4_vt_wheel002" position={[-74.727, 37.323, 130.31]} rotation={[Math.PI / 2, 0, 0]} scale={-106.747}>
                <mesh name="ARm4_vt_wheel002_ARm4_common_black_0" geometry={nodes.ARm4_vt_wheel002_ARm4_common_black_0.geometry} material={materials.ARm4_common_black} />
                <mesh name="ARm4_vt_wheel002_ARm4_main_0" geometry={nodes.ARm4_vt_wheel002_ARm4_main_0.geometry} material={materials.ARm4_main} />
                <mesh name="ARm4_vt_wheel002_ARm4_V_logo_0" geometry={nodes.ARm4_vt_wheel002_ARm4_V_logo_0.geometry} material={materials.ARm4_V_logo} />
                <mesh name="ARm4_vt_wheel002_michelin_diff_0" geometry={nodes.ARm4_vt_wheel002_michelin_diff_0.geometry} material={materials.michelin_diff} />
              </group>
              <group name="ARm4_vt_wheel003" position={[-74.727, 37.323, -150.797]} rotation={[Math.PI / 2, 0, 0]} scale={-106.747}>
                <mesh name="ARm4_vt_wheel003_ARm4_common_black_0" geometry={nodes.ARm4_vt_wheel003_ARm4_common_black_0.geometry} material={materials.ARm4_common_black} />
                <mesh name="ARm4_vt_wheel003_ARm4_main_0" geometry={nodes.ARm4_vt_wheel003_ARm4_main_0.geometry} material={materials.ARm4_main} />
                <mesh name="ARm4_vt_wheel003_ARm4_V_logo_0" geometry={nodes.ARm4_vt_wheel003_ARm4_V_logo_0.geometry} material={materials.ARm4_V_logo} />
                <mesh name="ARm4_vt_wheel003_michelin_diff_0" geometry={nodes.ARm4_vt_wheel003_michelin_diff_0.geometry} material={materials.michelin_diff} />
              </group>
              <group name="ARm4_windshield" rotation={[-Math.PI / 2, 0, 0]} scale={100}>
                <mesh name="ARm4_windshield_ARm4_glass_0" geometry={nodes.ARm4_windshield_ARm4_glass_0.geometry} material={materials.ARm4_glass} />
              </group>
              <group name="Object_4001" position={[75.519, 37.323, -150.797]} rotation={[-Math.PI / 2, 0, 0]} scale={90.462}>
                <mesh name="Object_4001_Scene_-_Root002_0" geometry={nodes['Object_4001_Scene_-_Root002_0'].geometry} material={materials['Scene_-_Root.002']} />
              </group>
              <group name="Object_4002" position={[-75.261, 37.323, 130.31]} rotation={[Math.PI / 2, 0, 0]} scale={-90.462}>
                <mesh name="Object_4002_Scene_-_Root002_0" geometry={nodes['Object_4002_Scene_-_Root002_0'].geometry} material={materials['Scene_-_Root.002']} />
              </group>
              <group name="Object_4003" position={[75.519, 37.323, 130.31]} rotation={[-Math.PI / 2, 0, 0]} scale={90.462}>
                <mesh name="Object_4003_Scene_-_Root002_0" geometry={nodes['Object_4003_Scene_-_Root002_0'].geometry} material={materials['Scene_-_Root.002']} />
              </group>
              <group name="Object_4004" position={[-75.261, 37.323, -150.797]} rotation={[Math.PI / 2, 0, 0]} scale={-90.462}>
                <mesh name="Object_4004_Scene_-_Root002_0" geometry={nodes['Object_4004_Scene_-_Root002_0'].geometry} material={materials['Scene_-_Root.002']} />
              </group>
            </group>
          </group>
        </group>
        <group name="Camera_target" position={[-0.058, 0.652, -0.25]} />
        <group name="NurbsPath" position={[0, 3.456, 0]} />
        <group name="Empty001" position={[-2.056, 1.961, -0.061]} />
       
        <PerspectiveCamera name="Camera_inside" makeDefault far={1000} near={0.1} fov={50.702} position={[0.412, 1.068, -0.354]} rotation={[-2.838, 0.062, 3.122]} />
      </group>
    </group>
   
  )
}

useGLTF.preload('/bmw_m4_f82.glb')
